
class CurrencyCodeMapping {
  Map<String, String> messageCode = {
    //!
    '៛':'KHR',
    'FBu':'BIF',
    'E':'SZL',
    'T':'TMT',
    'FCFA':'XAF',
    'VT':'VUV',
    'zł':'PLN',
    '₹':'INR',
    'A\$':'AUD',
    'Q':'GTQ',
    'XBC':'XBC',
    'Íkr':'ISK',
    '\$':'SRD',
    'GH₵':'GHS',
    'L':'MDL',
    'ZK':'ZMK',
    'XAG':'XAG',
    'C\$':'CAD',
    'Fr':'CHF',
    'L\$':'LRD',
    '₡':'CRC',
    'ر.ق':'QAR',
    'रू':'NPR',
    '¥':'CNY',
    'som':'UZS',
    'S/':'PEN',
    'MK':'MWK',
    'B\$':'BSD',
    'TSh':'TZS',
    'MT':'MZN',
    'RF':'RWF',
    '₣':'XPF',
    'HNL':'HNL',
    '﷼':'SAR',
    'Bds\$':'BBD',
    'دج':'DZD',
    '؋':'AFN',
    'ALL':'ALL',
    'XBA':'XBA',
    'Kr': 'SEK',
    'XBD':'XBD',


  };
}